#!/usr/local/bin/python3
from termcolor import cprint

import os
import sys
import json
#import helpers for displaying data
import display
#import helpers for adding data
import add
#import helpers for compiling cover letters
import parser

RED = 'red'
BLUE = 'blue'

if len(sys.argv) > 1:
    cover_letter_filename = sys.argv[1]
    data_filename = sys.argv[2]

    print(cover_letter_filename)
    print(data_filename)
